package WebdriverIDE;// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  public void tes() {
    // Test name: tes
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.baidu.com/");
    // 2 | setWindowSize | 1936x1056 |  | 
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | id=kw |  | 
    driver.findElement(By.id("kw")).click();
    // 4 | type | id=kw | 这是一个测试 | 
    driver.findElement(By.id("kw")).sendKeys("这是一个测试");
    // 5 | sendKeys | id=kw | ${KEY_ENTER} | 
    driver.findElement(By.id("kw")).sendKeys(Keys.ENTER);
    // 6 | click | linkText=测试你的内心有多强大? - 壹心理 |  | 
    vars.put("window_handles", driver.getWindowHandles());
    // 7 | selectWindow | handle=${win5034} |  | 
    driver.findElement(By.linkText("测试你的内心有多强大? - 壹心理")).click();
    // 8 | click | css=body |  | 
    vars.put("win5034", waitForWindow(2000));
    driver.switchTo().window(vars.get("win5034").toString());
    driver.findElement(By.cssSelector("body")).click();
  }
}
